# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
nav:
  - Home:
      - Introduction: index.md
      - Implementations: implementations.md

  - Server:
      - Get a Server: server/get-a-server.md
      - Get a Domain Name: server/get-a-domain-name.md
      - Remote Access: server/remote-access.md
      - Upgrade: server/upgrade.md
      - Firewall: server/firewall.md
      - Reverse Proxy: server/reverse-proxy.md
      - SSL/TLS Certificate: server/ssl-tls-certificate.md
      - Nostr User: server/nostr-user.md

  - Relays:
      - Khatru Pyramid:
          - Introduction: relays/khatru-pyramid/introduction.md
          - Build: relays/khatru-pyramid/build.md
          - Install: relays/khatru-pyramid/install.md
          - Configuration: relays/khatru-pyramid/configuration.md
          - Service: relays/khatru-pyramid/service.md
          - WebSocket Connection: relays/khatru-pyramid/websocket-connection.md
          - Test Your Relay: relays/khatru-pyramid/test.md

      - Nostream:
          - Introduction: relays/nostream/introduction.md
          - Build: relays/nostream/build.md
          - Install: relays/nostream/install.md
          - Configuration: relays/nostream/configuration.md
          - Service: relays/nostream/service.md
          - WebSocket Connection: relays/nostream/websocket-connection.md
          - Test Your Relay: relays/nostream/test.md

      - nostr-rs-relay:
          - Introduction: relays/nostr-rs-relay/introduction.md
          - Build: relays/nostr-rs-relay/build.md
          - Install: relays/nostr-rs-relay/install.md
          - Configuration: relays/nostr-rs-relay/configuration.md
          - Service: relays/nostr-rs-relay/service.md
          - WebSocket Connection: relays/nostr-rs-relay/websocket-connection.md
          - Test Your Relay: relays/nostr-rs-relay/test.md

      - strfry:
          - Introduction: relays/strfry/introduction.md
          - Build: relays/strfry/build.md
          - Install: relays/strfry/install.md
          - Configuration: relays/strfry/configuration.md
          - Service: relays/strfry/service.md
          - WebSocket Connection: relays/strfry/websocket-connection.md
          - Test Your Relay: relays/strfry/test.md
          - Upgrade: relays/strfry/upgrade.md

      - WoT Relay:
          - Introduction: relays/wot-relay/introduction.md
          - Build: relays/wot-relay/build.md
          - Install: relays/wot-relay/install.md
          - Configuration: relays/wot-relay/configuration.md
          - Service: relays/wot-relay/service.md
          - WebSocket Connection: relays/wot-relay/websocket-connection.md
          - Test Your Relay: relays/wot-relay/test.md

      - Khatru29:
          - Introduction: relays/khatru29/introduction.md
          - Build: relays/khatru29/build.md
          - Install: relays/khatru29/install.md
          - Configuration: relays/khatru29/configuration.md
          - Service: relays/khatru29/service.md
          - WebSocket Connection: relays/khatru29/websocket-connection.md
          - Test Your Relay: relays/khatru29/test.md

      - strfry29:
          - Introduction: relays/strfry29/introduction.md
          - Build: relays/strfry29/build.md
          - Install: relays/strfry29/install.md
          - Configuration: relays/strfry29/configuration.md
          - Service: relays/strfry29/service.md
          - WebSocket Connection: relays/strfry29/websocket-connection.md
          - Test Your Relay: relays/strfry29/test.md

  - FAQ:
      - Introduction: faq/index.md

  - Resources:
      - Nostr: resources/nostr.md
      - Nginx: resources/nginx.md

  - Contact:
      - NODE-TEC: contact/node-tec.md

  - Donate:
      - Bitcoin: donate/bitcoin.md
      - Fiat: donate/fiat.md

site_name: Relay Runner
site_url: https://relayrunner.org/
theme:
  font:
    code: IBM Plex Mono

  icon:
    view: material/eye

  name: material
  logo: assets/logo_cropped_purple.png
  favicon: assets/logo_square_purple.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    # - navigation.footer
    # - navigation.expand
    - navigation.path
    # - navigation.prune
    # - navigation.top
    # - navigation.indexes
    - navigation.tabs
    # - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    # - toc.follow
    # - toc.integrate
    - content.code.copy
    - content.action.edit
plugins:
  - search
  - social
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nodetec
      name: NODE-TEC on GitHub
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@nodetec
      name: NODE-TEC on YouTube
    - icon: fontawesome/solid/bookmark
      link: https://nodetec.substack.com/
      name: NODE-TEC Substack
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/nodetec
      name: NODE-TEC on Keybase
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/node_tec
      name: NODE-TEC on X
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zdKq5brhF9
      name: NODE-TEC on Discord
    - icon: fontawesome/solid/envelope
      link: mailto:devs@node-tec.com
      name: NODE-TEC Email

repo_url: https://github.com/nodetec/relayrunner
repo_name: NODE-TEC/relayrunner
edit_uri: edit/master/docs/

copyright: Copyright &copy; 2024 NODE-TEC
