# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
nav:
  - Home:
      - Introduction: index.md
      - Implementations: implementations.md
      - Contact: contact.md
      - Resources: resources.md
      - FAQ: faq.md

  - Server:
      - Get a Server: server/get-a-server.md
      - Get a Domain Name: server/get-a-domain-name.md
      - Remote Access: server/remote-access.md
      - Upgrade: server/upgrade.md
      - Firewall: server/firewall.md
      - Reverse Proxy: server/reverse-proxy.md
      - SSL/TLS Certificate: server/ssl-tls-certificate.md
      - Nostr User: server/nostr-user.md

  - Relay:
      - Khatru Pyramid:
          - Intro: relay/khatru-pyramid/intro.md
          - Build: relay/khatru-pyramid/build.md
          - Install: relay/khatru-pyramid/install.md
          - Configuration: relay/khatru-pyramid/configuration.md
          - Service: relay/khatru-pyramid/service.md
          - WebSocket Connection: relay/khatru-pyramid/websocket-connection.md
          - Test Your Relay: relay/khatru-pyramid/test.md

      - Nostream:
          - Intro: relay/nostream/intro.md
          - Build: relay/nostream/build.md
          - Install: relay/nostream/install.md
          - Configuration: relay/nostream/configuration.md
          - Service: relay/nostream/service.md
          - WebSocket Connection: relay/nostream/websocket-connection.md
          - Test Your Relay: relay/nostream/test.md

      - nostr-rs-relay:
          - Intro: relay/nostr-rs-relay/intro.md
          - Build: relay/nostr-rs-relay/build.md
          - Install: relay/nostr-rs-relay/install.md
          - Configuration: relay/nostr-rs-relay/configuration.md
          - Service: relay/nostr-rs-relay/service.md
          - WebSocket Connection: relay/nostr-rs-relay/websocket-connection.md
          - Test Your Relay: relay/nostr-rs-relay/test.md

      - strfry:
          - Intro: relay/strfry/intro.md
          - Build: relay/strfry/build.md
          - Install: relay/strfry/install.md
          - Configuration: relay/strfry/configuration.md
          - Service: relay/strfry/service.md
          - WebSocket Connection: relay/strfry/websocket-connection.md
          - Test Your Relay: relay/strfry/test.md
          - Upgrade: relay/strfry/upgrade.md

      - WoT Relay:
          - Intro: relay/wot-relay/intro.md
          - Build: relay/wot-relay/build.md
          - Install: relay/wot-relay/install.md
          - Configuration: relay/wot-relay/configuration.md
          - Service: relay/wot-relay/service.md
          - WebSocket Connection: relay/wot-relay/websocket-connection.md
          - Test Your Relay: relay/wot-relay/test.md

      - Khatru29:
          - Intro: relay/khatru29/intro.md
          - Build: relay/khatru29/build.md
          - Install: relay/khatru29/install.md
          - Configuration: relay/khatru29/configuration.md
          - Service: relay/khatru29/service.md
          - WebSocket Connection: relay/khatru29/websocket-connection.md
          - Test Your Relay: relay/khatru29/test.md

      - strfry29:
          - Intro: relay/strfry29/intro.md
          - Build: relay/strfry29/build.md
          - Install: relay/strfry29/install.md
          - Configuration: relay/strfry29/configuration.md
          - Service: relay/strfry29/service.md
          - WebSocket Connection: relay/strfry29/websocket-connection.md
          - Test Your Relay: relay/strfry29/test.md

  - Donate:
      - bitcoin: donate/index.md

site_name: Relay Runner
site_url: https://relayrunner.org/
theme:
  font:
    code: IBM Plex Mono

  icon:
    view: material/eye

  name: material
  logo: assets/logo_cropped_purple.png
  favicon: assets/logo_square_purple.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    # - navigation.footer
    # - navigation.expand
    - navigation.path
    # - navigation.prune
    # - navigation.top
    # - navigation.indexes
    - navigation.tabs
    # - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    # - toc.follow
    # - toc.integrate
    - content.code.copy
    - content.action.edit
plugins:
  - search
  - social
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/node_tec
      name: NODE-TEC on Twitter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@nodetec
      name: NODE-TEC on YouTube
    - icon: fontawesome/brands/github
      link: https://github.com/nodetec
      name: NODE-TEC on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zdKq5brhF9
      name: NODE-TEC on Discord

repo_url: https://github.com/nodetec/relayrunner
repo_name: NODE-TEC/relayrunner
edit_uri: edit/master/docs/

copyright: Copyright &copy; 2024 NODE-TEC
